{application,phx_gen_auth,
             [{applications,[kernel,stdlib,elixir,logger,phoenix]},
              {description,"An authentication system generator for Phoenix 1.5+"},
              {modules,['Elixir.Mix.Phx.Gen.Auth.HashingLibrary',
                        'Elixir.Mix.Phx.Gen.Auth.Injector',
                        'Elixir.Mix.Phx.Gen.Auth.Injectors.RouterPlug',
                        'Elixir.Mix.Phx.Gen.Auth.Migration',
                        'Elixir.Mix.Tasks.Phx.Gen.Auth']},
              {registered,[]},
              {vsn,"0.3.0"}]}.
